FROM openjdk:17-jdk-slim

ADD target/ca-cmc-admin-client-1.0.6-SNAPSHOT.jar /app.jar

# This ENTRYPOINT enables attachement of a debugger on port 8000. This port is automtically exposed on the docker container.
ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000","-jar","/app.jar"]

# Main web port
EXPOSE 8080
# HTTPS web port
EXPOSE 8443
# AJP port
EXPOSE 8009
